name: commercia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  #utility
  http: ^1.1.0
  intl: ^0.20.2
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.5
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.0.0


  #icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2


    #state management
  get: ^4.6.5
  get_storage: ^2.1.1
  lottie: ^3.3.1

  #product specific
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/images/on_boarding_images/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/
    - assets/images/reviews/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800


